export default {
    MEETING_EVENT_CHANGE: 'MEETING_EVENT_CHANGE',
    MEETING_CREATE_UPDATE: 'MEETING_CREATE_UPDATE',
    MEETING_DELETE: 'MEETING_DELETE',
    STORE_KEY_ITEM: '@MeetingStore:meeting:id:'
}